import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import LenisWrapper from "@/components/LenisWrapper";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/lenis@1.3.15/dist/lenis.css"></link>
      </head>
      <body className={`${ubuntu.variable} antialiased`}>
        <LenisWrapper>
          {children}
        </LenisWrapper>
        
      </body>
    </html>
  );
}
